name: Publish on Space

on: [push, pull_request]

jobs:
  publish:
    name: kek
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SetUp Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Add properties and publish
        run: |
          echo ${{ secrets.SPACE_NAME }} >> gradle.properties
          echo ${{ secrets.SPACE_TOKEN }} >> gradle.properties
          ./gradlew publish
